run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
  disable:
    - depguard

linters-settings:
  goimports:
    local-prefixes: github.com/phoeluga/synology-proxy-operator

issues:
  exclude-rules:
    - path: zz_generated
      linters:
        - all
