---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: synology-proxy-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - proxy.synology.io
  resources:
  - synologyproxyrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.synology.io
  resources:
  - synologyproxyrules/finalizers
  verbs:
  - update
- apiGroups:
  - proxy.synology.io
  resources:
  - synologyproxyrules/status
  verbs:
  - get
  - patch
  - update
