apiVersion: v1
kind: ServiceAccount
metadata:
  name: synology-proxy-operator
  namespace: synology-proxy-operator
  labels:
    app.kubernetes.io/name: synology-proxy-operator
    app.kubernetes.io/component: controller
automountServiceAccountToken: true
