//go:build !ignore_autogenerated

/*
Copyright The synology-proxy-operator authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomHeader) DeepCopyInto(out *CustomHeader) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomHeader.
func (in *CustomHeader) DeepCopy() *CustomHeader {
	if in == nil {
		return nil
	}
	out := new(CustomHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedRecord) DeepCopyInto(out *ManagedRecord) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedRecord.
func (in *ManagedRecord) DeepCopy() *ManagedRecord {
	if in == nil {
		return nil
	}
	out := new(ManagedRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectRef) DeepCopyInto(out *ObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectRef.
func (in *ObjectRef) DeepCopy() *ObjectRef {
	if in == nil {
		return nil
	}
	out := new(ObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyTimeouts) DeepCopyInto(out *ProxyTimeouts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyTimeouts.
func (in *ProxyTimeouts) DeepCopy() *ProxyTimeouts {
	if in == nil {
		return nil
	}
	out := new(ProxyTimeouts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynologyProxyRule) DeepCopyInto(out *SynologyProxyRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynologyProxyRule.
func (in *SynologyProxyRule) DeepCopy() *SynologyProxyRule {
	if in == nil {
		return nil
	}
	out := new(SynologyProxyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SynologyProxyRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynologyProxyRuleList) DeepCopyInto(out *SynologyProxyRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SynologyProxyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynologyProxyRuleList.
func (in *SynologyProxyRuleList) DeepCopy() *SynologyProxyRuleList {
	if in == nil {
		return nil
	}
	out := new(SynologyProxyRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SynologyProxyRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynologyProxyRuleSpec) DeepCopyInto(out *SynologyProxyRuleSpec) {
	*out = *in
	if in.AdditionalSourceHosts != nil {
		in, out := &in.AdditionalSourceHosts, &out.AdditionalSourceHosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AssignCertificate != nil {
		in, out := &in.AssignCertificate, &out.AssignCertificate
		*out = new(bool)
		**out = **in
	}
	if in.CustomHeaders != nil {
		in, out := &in.CustomHeaders, &out.CustomHeaders
		*out = make([]CustomHeader, len(*in))
		copy(*out, *in)
	}
	if in.ServiceRef != nil {
		in, out := &in.ServiceRef, &out.ServiceRef
		*out = new(ObjectRef)
		**out = **in
	}
	if in.IngressRef != nil {
		in, out := &in.IngressRef, &out.IngressRef
		*out = new(ObjectRef)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(ProxyTimeouts)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynologyProxyRuleSpec.
func (in *SynologyProxyRuleSpec) DeepCopy() *SynologyProxyRuleSpec {
	if in == nil {
		return nil
	}
	out := new(SynologyProxyRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynologyProxyRuleStatus) DeepCopyInto(out *SynologyProxyRuleStatus) {
	*out = *in
	if in.ManagedRecords != nil {
		in, out := &in.ManagedRecords, &out.ManagedRecords
		*out = make([]ManagedRecord, len(*in))
		copy(*out, *in)
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynologyProxyRuleStatus.
func (in *SynologyProxyRuleStatus) DeepCopy() *SynologyProxyRuleStatus {
	if in == nil {
		return nil
	}
	out := new(SynologyProxyRuleStatus)
	in.DeepCopyInto(out)
	return out
}
