{{- if not .Values.synology.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synology-proxy-operator.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synology-proxy-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  SYNOLOGY_URL: {{ .Values.synology.url | quote }}
  SYNOLOGY_USER: {{ .Values.synology.username | quote }}
  SYNOLOGY_PASSWORD: {{ .Values.synology.password | quote }}
{{- end }}
